#!/bin/bash
## This file is managed by Puppet; changes may be overwritten.

quadbox=lsstcam-rebps,lsstcam-fcs,lsstcam-quad,lsstcam-vac

user=ccs

poweroff="/usr/local/bin/CCS_POWEROFF"


[ "$(id -un)" = $user ] && {
    echo "You are currently $user"
    echo "You must run this command from your normal account"
    exit 1
}

shost=${HOSTNAME%%.*}

case $quadbox in
    *$shost*) : ;;
    *) echo "You must run this from a quadbox host"; exit 1 ;;
esac


[ "$1" = "-y" ] || {
    echo "Preparing to shutdown quadbox: $quadbox"
    read -n 1 -p "y to proceed, else quit: " -r reply
    echo
    [ "$reply" = "y" ] || {
        echo "aborted"
        exit 0
    }
}


echo "Shutting down remote hosts, enter your password..."
clush -m sudo -w "$quadbox"\!"$shost" -- -u $user "$poweroff" -y


echo "Shutting down this host, if prompted enter your password..."
sudo -u $user "$poweroff" "$1"
