#!/bin/bash
## This file is managed by Puppet; changes may be overwritten.

task=$1

case $task in
    reboot|poweroff) : ;;
    *) echo "bad task: $task" ; exit 1;;
esac

shift

[ "$1" = "-y" ] || {
  read -n 1 -p "y to $task, else quit: " -r reply
  echo
  [ "$reply" = "y" ] || {
    echo "aborted"
    exit 0
  }
}


sudo_user=ccs
prefix=
prefix2=sudo

if [ $UID -eq 0 ]; then
    prefix2=
else
    [ "$(id -un)" = $sudo_user ] || prefix="sudo -u $sudo_user"
fi

## Do not quote prefix, prefix2.
$prefix $prefix2 /usr/bin/systemctl "$task"
